POST http://localhost:5000/cotacao/
Content-Type: application/json

{
  "tamanho": 120,
  "ano": 2001,
  "garagem": 2
}

###
POST http://localhost:5000/cotacao2/
Content-Type: application/json

{
  "tamanho": 120,
  "ano": 2001,
  "garagem": 2
}

###
POST http://localhost:5000/
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
GET http://localhost:5000/sentimento/Eu odeio Itaborai
Accept: application/json

###
GET http://localhost:5000/houseprices1/30
Accept: application/json


